### ISSUE TITLE
Allow custom http.Client ?

### ISSUE THREAD

**Issue by aerth** [joeybloggs/go-download#2]
offer ability to use custom http.Client instead using default http.Client

**Comment by deankarn** [comment]
I'll look into it thanks

**Comment by deankarn** [comment]
Hey @aerth I've made some changes to allow for overriding the http.Client and another for access to the http.Request object in the v2 branch.

via the options, 
```go
options := &download.Options{
		Client: func() http.Client{
                      // return  custom client.....
                },
	}
```

would you be able to check it out before I merge into master?

**Comment by aerth** [comment]
you rock! Custom http.Client works great, thanks!

**Comment by aerth** [comment]
### Custom `http.Client` only is being used for some operations

**Comment by deankarn** [comment]
I'll correct that for the head request

**Comment by deankarn** [comment]
ok @aerth  HEAD now uses custom client function as well.
